[package]
name = "libsimple"
version = "0.8.0"
authors = ["xuxiaocheng <2762267080@qq.com>"]
edition = "2024"
rust-version = "1.85.0"
description = "Rust bindings to simple, a SQLite3 fts5 tokenizer which supports Chinese and PinYin."
readme = "README.md"
license = "MIT"
repository = "https://github.com/xuxiaocheng0201/libsimple/"
documentation = "https://docs.rs/libsimple/"
categories = ["database"]
keywords = ["sqlite", "extension", "sqlite-extension", "fts5", "tokenizer"]

include = [
    "/Cargo.toml",
    "/README.md",
    "/src",
    "/build.rs",
    "/examples",
    "/tests",
    "/patch/*.patch",

    "/cppjieba/include",
    "/cppjieba/dict",
    "!/cppjieba/dict/pos_dict",
    "/cppjieba/deps/limonp/include",
    "/simple/src",
    "/simple/contrib/sqlite3",
    "/simple/contrib/pinyin.txt",

    "**/LICENSE",
    "**/CMakeLists.txt",
    "**/*.cmake",
]

[features]
default = ["jieba"]
jieba = []

[build-dependencies]
cc = { version = "^1", features = ["parallel"] }

[dependencies]
rusqlite = ">=0.32,<1.0"
better_embedded = { version = "~0.4", default-features = false }

[dev-dependencies]
anyhow = "^1"
rusqlite = { version = ">=0.32,<1.0", features = ["bundled"] }
tempfile = "^3"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[example]]
name = "hello"
test = true

[[test]]
name = "custom_pinyin"
[[test]]
name = "simple_example"
[[test]]
name = "ffi_linked"
