name: CI

permissions:
  contents: read

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  test:
    strategy:
      matrix:
        os:
          - name: linux-amd64
            runner: ubuntu-latest
          - name: linux-arm64
            runner: ubuntu-24.04-arm
          - name: windows-amd64
            runner: windows-latest
          - name: windows-arm64
            runner: windows-11-arm
          - name: macos-arm64
            runner: macos-latest
          - name: macos-amd64
            runner: macos-15-intel
      fail-fast: false
    name: Test on ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Check rust version
        run: rustup --version
      - name: Run test
        run: cargo test
